### ISSUE TITLE
Tries were kept from one day to the next

### ISSUE THREAD

**Issue by maxenceg** [julienc91/caviardeul#1]
Hello Julien !

Je pense que je peux t'écrire en français sans souci 😉 

J'aime beaucoup ton adaptation de Redactle, ça fait plaisir de voir une nouvelle adaptation en français !

J'ai commencé une partie hier avant minuit (sans trouver le caviardeul), et en voulant rejouer aujourd'hui, mes essais de la veille avaient été conservés pour le caviardeul du jour (j'ai donc commencé au 58e essai au lieu du 1er)

D'ailleurs, quand je clique sur "peintre", qui avait des occurrences hier, rien ne se passe car il n'y a pas d'occurrence aujourd'hui

<img width="1780" alt="image" src="https://user-images.githubusercontent.com/38657323/170821896-4d6a3102-bf70-4743-b0d4-3a89bcb5426b.png">

**Comment by maxenceg** [comment]
@julienc91 Je rajouterais que j'ai voulu faire le caviardeul d'aujourd'hui, mais que les essais de la veille avaient été gardés et la page était déjà dévoilée (sans que je ne l'aie jouée)

**Comment by julienc91** [comment]
@maxenceg Je n'arrive pas à trouver la source du problème, la sauvegarde automatique est en principe supprimée sans être chargée lorsqu'elle ne correspond pas à l'article du jour... Pourrais-tu exécuter cette commande dans une console JS de ton navigateur tout en étant sur le site, et me faire parvenir le résultat ?

```
["key", "progress"].map(k => localStorage.getItem(k))
```

**Comment by julienc91** [comment]
En fait je pense avoir trouvé l'erreur: les données relatives à l'article wikipedia du jour sont chargées via un appel API, et celui-ci était régulièrement rafraîchi par erreur. Une désynchronisation pouvait alors se produire lorsque l'article initialement chargé était différent de celui obtenu après rafraîchissement. Je considère le sujet clos, mais n'hésite pas à rouvrir si de nouvelles erreurs sont constatées !

Commit f6998030ac7f7324f1ef7f2077ecad8c126d1a8b
