### ISSUE TITLE
dû et du ne sont pas considérés comme identiques

### ISSUE THREAD

**Issue by maxenceg** [julienc91/caviardeul#12]
<img width="312" alt="image" src="https://user-images.githubusercontent.com/38657323/195833318-c63f218e-3e97-4b2a-a71f-31f1b8bc2cf5.png">

Le mot "du" (sans accent) est révélé au début des parties, mais pas le mot "dû" pourtant équivalent dans le jeu

Ce qui fait que pour révéler "dû", j'ai d'abord tapé "du", qui n'a pas marché car déjà révélé, puis j'ai tapé "dû" qui a été assimilé à "du" mais révélant le mot "dû"

**Comment by julienc91** [comment]
"It's not a bug, it's a feature" 😀 C'est un comportement qui a été souhaité (c6713abe56bd80946384df0dfb37ae849c725585) afin de ne pas révéler des quasi-homographes (après => âpres, ne => né, du => dû) qui ne sont pas considérés comme des mots courants. Je reconnais que ce cas particulier n'est pas indiqué clairement dans les règles, mais j'ai considéré que les mots concernés étaient suffisamment peu nombreux pour ne pas complexifier l'introduction au jeu en rajoutant une section dédiée à cette règle.

**Comment by maxenceg** [comment]
Ok très clair !

Je me suis laissé trompé par d'autres mots comme "des" ("dès" est automatiquement révélé mais il est peut-être considéré comme courant)
