### ISSUE TITLE
Toggle "reveal close words" options after one guess displays a blank page

### ISSUE THREAD

**Issue by ShaigroRB** [julienc91/caviardeul#14]
Hey.

After guessing a word that reveals close words of it, if I toggle the option "Reveal close word" or reload the page, it displays a blank page with the error: `Application error: a client-side exception has occurred (see the browser console for more information)`.

The error in the console is `Error: Cannot count occurrences of common word: ne`.

Here a gif showing the problem:  
![caviardeul_broken_close_words](https://user-images.githubusercontent.com/17238438/200567168-68dd82b8-496c-47b3-92f6-ac4d2fc87145.gif)

**Comment by julienc91** [comment]
Thanks for the feedback, fixed in 3c1253d873658850b6a4a52298fa0c1081995513
