### ISSUE TITLE
Statistiques perdues 🥲

### ISSUE THREAD

**Issue by maxenceg** [julienc91/caviardeul#15]
J'ai dû fermer Chrome et le mettre à jour, mais en tout cas j'ai perdu toutes mes statistiques depuis le début 🥲

Est-ce qu'il y a moyen de les "récupérer" ? Tout passe par le cache du navigateur, on peut pas créer un compte ?

**Comment by julienc91** [comment]
Si tu as associé un second appareil à ton compte, la solution la plus simple consiste à réutiliser cette fonctionnalité à partir du second appareil vers le premier.
Autrement, j'ai la possibilité de retrouver ton identifiant de joueur, et ainsi de générer l'url de synchronisation de compte, mais j'aurai besoin pour cela de connaître tes scores exacts sur plusieurs jours (par exemple 137 sur la partie 18, 148 sur la partie 19, etc), pour que j'arrive à retrouver l'entrée depuis la base de données (=> passe par mail dans ce cas, sur contact arobase caviardeul point fr).
