### ISSUE TITLE
Article du 2023-06-21 affiché directement avec stats du 2023-06-20

### ISSUE THREAD

**Issue by cyril-amar** [julienc91/caviardeul#17]
### Constaté
Le 2023-06-21, en allant sur `https://caviardeul.fr/`, l'article complet est affiché directement alors que je ne l'ai pas joué.
Le bandeau de droite affiche mes statistiques et liste d'essais de la veille.
`CTRL`+`F5` ne permet pas de résoudre le problème.

### Attendu
Le panneau de gauche affiche l'article caviardé.
Le panneau de droite n'affiche pas les statistiques et une liste d'essai vierge.

**Comment by julienc91** [comment]
Bonjour Cyril,
Pourrais-tu aller sur la page https://caviardeul.fr/debug et me faire parvenir les informations qui y sont affichées à l'adresse contact[at]caviardeul.fr
Merci d'avance

**Comment by cyril-amar** [comment]
Bonjour Julien,
C'est fait :)

**Comment by cyril-amar** [comment]
Petit supplément d'info : le 391 (celui du 21 juin) est considéré comme résolu avec les mêmes stats que le 390. Ce n'était pas seulement un mix d'affichage comme mon report le laissait penser : 
![image](https://github.com/julienc91/caviardeul/assets/24855141/1936cf0a-7411-4cef-a6b5-19621369a25b)

**Comment by julienc91** [comment]
@cyril-amar Je n'ai malheureusement pas encore eu le temps de me pencher sérieusement sur ce problème... J'ai peut-être une hypothèse, mais j'aurais besoin d'infos supplémentaires : 
* est-ce que l'onglet de caviardeul était "épinglé" sur ton navigateur, ou resté ouvert entre le jour 390 et le jour 391 ? Ou as-tu ouvert caviardeul sur un nouvel onglet ?
* le 391 est-il apparu comme résolu dès l'ouverture du site ? ou y'a t-il eu un laps de temps où ce n'était pas le cas ?
Merci d'avance !

**Comment by cyril-amar** [comment]
Pas de souci !

- L'onglet n'est pas épinglé mais il reste ouvert en permanence, depuis plus de 2 semaines à ce stade.
- Le 391 est apparu résolu dès que j'ai actualisé l'onglet pour la première fois.

**Comment by julienc91** [comment]
Je pense avoir trouvé le problème : sous certaines conditions le jeu pouvait se charger avec l'article du jour tout en conservant l'état d'avancement de la dernière partie. Cette situation pouvait arriver notamment lorsque la page d'accueil du site restait ouverte plusieurs jours de suite.

Corrigé sur 4cdaa167aa092b4a9d21b593a184fe301d9bd0ee
