### ISSUE TITLE
CAVIARDEUL 85

### ISSUE THREAD

**Issue by Sosuke72** [julienc91/caviardeul#36]
Bonjour,

Je me permet de t'envoyer ce message car le caviardeul numéro 85 est une page de renvoi.

Serait-il possible de le modifier.
 
![image](https://github.com/user-attachments/assets/95207894-5c04-47f5-b89b-b4a9ce8e6849)

Merci par avance pour ton retour.

**Comment by julienc91** [comment]
Merci pour le signalement, c'est corrigé ! Je vais essayer de faire en sorte d'être notifié automatiquement la prochaine fois que ça arrivera
