### ISSUE TITLE
Partie comptée deux fois

### ISSUE THREAD

**Issue by maxenceg** [julienc91/caviardeul#8]
Je ne sais pas si c'est en rapport avec le fix d'hier, mais en jouant la partie d'hier (je n'ai pas rafraichi ma page depuis hier, et n'avais pas commencé le caviardeul du jour), puis en rafraîchissant la page, je me suis retrouvé sur la partie d'aujourd'hui, déjà dévoilée, et dans les archives, on m'a compté les mêmes statistiques pour les deux parties :

![187214020-57949aa2-2946-4b8d-b69c-6f0ed5980a82](https://user-images.githubusercontent.com/2772915/187256156-6bc7c975-3156-48a1-ad23-73b82d1c4e17.png)

**Comment by maxenceg** [comment]
Je suis sur Chrome, j'essaierai de mieux détailler la prochaine fois, il faut que je sois vigilant !

**Comment by julienc91** [comment]
@maxenceg J'ai créé une page pour partager des informations de debug, si ça se reproduit, ça me serait très utile d'avoir accès à ces infos :slightly_smiling_face: `caviardeul.fr/debug`
